
#  pool:
#    core-pool-size: 8
#    max-pool-size: 12
#    keep-alive-time-in-millis: 30000
#    queue-capacity: 200

#ok:
#  http:
#    connect-timeout: 120s
#    read-timeout: 300s
#    write-timeout: 60s
#  # 连接池中整体的空闲连接的最大数量
#    max-idle-connections: 3
#  # 连接空闲时间最多为 300 秒
#    keep-alive-duration: 300s

server:
  port: 9014
  servlet:
    context-path: /client2

spring:
  application:
    name: client2
#  kafka:
#    producer:
#      acks: all
#      #可配置多个kafka节点地址用','分隔
#      bootstrap-servers: 192.168.3.3:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#      retries: 5
#      client-id: pic-sender
#      batch-size: 3
# dubbo 方法一 配置
  dubbo:
    scan: dubbo.service
    application:
     name: ${spring.application.name}
    registry:
      address: 192.168.93.128:2181
      protocol: zookeeper

    protocol:
      name: rmi
      port: 20883
      transporter: netty
      threadpool: fixed
      threads: 1
      queue: 100
      parameters:
        threadname: dubbo-client2

    monitor:
      protocol: registry



logger:
  level: info
  path: /data/log/dubbo-server2
  console:
    level: info

logging:
  config: classpath:logback-spring.xml




